devices([
  "iPhone 16 Pro Max",
  "iPad Pro 13-inch (M4)"
])

languages(["en-US"])

scheme("rhymate")

test_target_name("rhymateUITests")

xcargs("-only-testing:rhymateUITests/SnapshotTests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
